[package]

name = "rustgb"
version = "0.0.1"
authors = ["Jaume Delcl√≤s Coll <cosa.rara97@gmail.com>"]

[dependencies.sdl]
git = "https://github.com/brson/rust-sdl.git"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"

[dependencies]
getopts = "0.2.4"


